# Generated by Django 2.0.5 on 2018-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180624_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
